FROM alpine:procon30-solver-base

ARG SOURCE_PY="solver.py"
COPY $SOURCE_PY /tmp/solver.py

RUN     echo "[INFO] Setup solver.py" && \
        cd /tmp && \
        echo "#!/usr/bin/env python3" > test.py && \
        echo "import numpy" >> test.py && \
        chmod +x test.py && \
        chmod +x solver.py && \
        ./test.py
