FROM alpine:latest

RUN     echo "[Info] Start Build..." && \
        set -x && \
        echo "[Info] Install Packages..." && \
        apk --update --no-cache add \
                python3 \
                python3-dev \
                gcc \
                g++ \
                make \
                musl \
                musl-dev \
                linux-headers \
                gfortran \
                openblas-dev && \
        echo "[Info] Insall Python libaries..." && \
        pip3 install --upgrade pip && \
        pip3 install numpy
